import React from 'react'
import styled from 'styled-components'
import remedialIcon from '../images/icons/icons8-massage-100.png'
import pregnancyIcon from '../images/icons/icons8-pregnant-100.png'
import deepTissueIcon from '../images/icons/icons8-acupressure-100.png'
import aromatherapyIcon from '../images/icons/icons8-oil-massage-100.png'

const TreatmentsStyles = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 25vh;
  .wrapper {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 3rem 5rem;
  }
  .card {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: var(--grey);
    padding: 2rem;
    border-radius: 1rem;
  }
  .shadow-drop-2-center:hover {
    animation: shadow-drop-2-center 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
      both;
  }
  @media (max-width: 640px) {
    .wrapper {
      grid-template-columns: 1fr;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-2-28 10:7:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation shadow-drop-2-center
 * ----------------------------------------
 */
  @keyframes shadow-drop-2-center {
    0% {
      transform: translateZ(0);
      box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
    }
    100% {
      transform: translateZ(80px);
      box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
    }
  }
`
export const Treatments = () => {
  return (
    <TreatmentsStyles>
      <h3>Treatments</h3>
      <div className="wrapper">
        {data.map((item, index) => {
          return (
            <div
              className="card shadow-drop-2-center"
              key={`${item.name}-${index}`}
            >
              <img
                src={item.icon}
                alt={item.name}
                style={{ width: '50px', marginRight: '2rem' }}
              />
              <h4>{item.name}</h4>
            </div>
          )
        })}
      </div>
    </TreatmentsStyles>
  )
}

const data = [
  {
    name: 'Remedial Massage',
    icon: `${remedialIcon}`,
  },
  {
    name: 'Pregnancy Massage',
    icon: `${pregnancyIcon}`,
  },
  {
    name: 'Deep Tissue Massage',
    icon: `${deepTissueIcon}`,
  },
  {
    name: 'Aromatherapy Massage',
    icon: `${aromatherapyIcon}`,
  },
  // {
  //   name: 'Relaxation Massage',
  // },
  // {
  //   name: 'Hot Stone Massage',
  // },
  // {
  //   name: 'Tibetan Singing Bowl Therapy Sounds Massage',
  // },
]
